#! /bin/bash
IMAGE_FOLDER=$HOME/config/bgimages
IMAGE="$(ls $IMAGE_FOLDER/* | grep -i '\.\(png\|jpe\?g\)$' | sort -R | tail -n1)"
echo $IMAGE
gsettings set org.gnome.desktop.background picture-uri file://$IMAGE
