#! /usr/bin/python3

import requests
import pprint
import sys

if len(sys.argv) != 3:
    print("repocreate reponame \"description of repository\"")
    quit()

name = sys.argv[1]
desc = sys.argv[2]

URL = "https://api.github.com/user/repos"
TOKEN = "eae37ee5658421bb99dc2516e94ea7e085bcf91a"

HEADER = {"Authorization" : "token {}".format(TOKEN)}
PAYLOAD = {"name" : name, "description" : desc }

r = requests.post(URL, headers=HEADER, json=PAYLOAD)
results = r.json()

if "ssh_url" in results:
    print(results["ssh_url"])
else:
    pprint(results)
