#!/usr/bin/python3

import sys
import os
import re

MAXLEN = 60
inputpath = os.getcwd()

if len(sys.argv) > 2:

else:
    inputpath = os.getcwd()

# sub ~ for base of home directory
inputpath = re.sub('^'+ os.getenv('HOME'), '~', inputpath)

# split anything before the first slash (like ~) from the rest of the path
PATHBASE= r'^([^/]*)'
RESTPATH= r'(.*)$'
match = re.search(PATHBASE+RESTPATH, inputpath)

try:
    base = match.group(1)
    path = match.group(2)
except IndexError:
    # when regular expressions fail to match, print the path and quit
    print(inputpath)
    quit()

while len(base + path) > MAXLEN:
    # separate top subdir in path from the rest
    FIRSTCHUNK= r'^(/[^/]*)'
    REST= r'(/.*)$'
    try:
        match = re.search(FIRSTCHUNK + REST, path)
        first = match.group(1)
        rest = match.group(2)
    except AttributeError:
        # when regular expressions fail to match, print the path and quit
        print(base+path)
        quit()
    if len(first) > 2:
        # shorten the top subdir
        first = first[0:2]
    # add the shortened dir to base
    base = base + first
    # loop with the unshortened portion as path
    path = rest

print(base+path)
